os: linux
sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7-dev
      env: TOXENV=py
install:
  - pip install tox
cache:
  - pip
script:
  - tox
