[tox]
envlist=py{312,313,314}
skip_missing_interpreters=True

[testenv]
deps=-rrequirements-dev.txt
commands=
    pytest {posargs:tests/}
allowlist_externals=make

[testenv:dev]
deps=-rrequirements-dev.txt
usedevelop=True
